# shellcheck shell=bash
# Findings bridge (R7): normalize reviewer threads + failing CI checks into
# BMAD's review-findings format. Each item carries a machine tag
# (<!-- thread:<id> --> / <!-- check:<name> -->) so `rereview
# --resolve-addressed` can resolve exactly the checked-off threads.

findings_path() {
  printf '%s/%s-findings.md' "$(ledger_dir)" "$(sanitize_key "$1")"
}

# findings_render <key> <pr_number> <threads_json> <failing_checks_json>
#                 <score> <approved> → markdown on stdout
findings_render() {
  local key=$1 pr=$2 threads_json=$3 checks_json=$4 score=$5 approved=$6
  local n_threads n_checks
  n_threads="$(jq 'length' <<<"$threads_json")"
  n_checks="$(jq 'length' <<<"$checks_json")"

  cat <<EOF
# PR review findings — story $key (PR #$pr)

Generated by \`bmad-pr ingest\` at $(now_iso). Provider: ${BMAD_PR_REVIEWER:-none}.

Address each finding like a BMAD code-review finding: patch it, or defer it
with a DW entry in deferred-work.md, or dismiss it with a stated reason.
Mark addressed items \`[x]\`, then run:
\`bmad-pr rereview --story $key --resolve-addressed\`

## Summary

- Reviewer score: ${score:-n/a}${score:+/10} (threshold: ${BMAD_PR_SCORE_THRESHOLD:-n/a})
- Reviewer approved: $approved
- Unresolved reviewer threads: $n_threads
- Failing CI checks: $n_checks

## Findings
EOF

  if ((n_threads == 0 && n_checks == 0)); then
    printf '\nNone — the PR is clean from this provider'\''s perspective.\n'
    return 0
  fi
  printf '\n'

  jq -r '
    def title:
      (.body // "" | split("\n") | map(select(length > 0)) | .[0] // "reviewer finding")
      | gsub("[*_`#>]"; "") | gsub("^\\s+|\\s+$"; "") | .[0:120];
    def excerpt:
      (.body // "" | split("\n") | map(select(length > 0)) | .[1:4] | join("\n  > "));
    .[]
    | "- [ ] [Review][Patch] \(title) [\(.path // "?"):\(.line // "?")] <!-- thread:\(.id) -->"
      + (if excerpt == "" then "" else "\n  > " + excerpt end)
  ' <<<"$threads_json"

  jq -r '
    .[]
    | "- [ ] [Review][Patch] CI check failing: \(.name)\(.description // "" | if . == "" then "" else " — " + . end) <!-- check:\(.name) -->"
      + (if (.link // "") == "" then "" else "\n  > \(.link)" end)
  ' <<<"$checks_json"
}

# findings_addressed_thread_ids <key> — thread ids of checked-off items.
findings_addressed_thread_ids() {
  local file
  file="$(findings_path "$1")"
  [[ -f "$file" ]] || return 0
  sed -n 's/^- \[[xX]\] .*<!-- thread:\([A-Za-z0-9_=-]*\) -->.*/\1/p' "$file"
}

# findings_open_count <key> — unchecked items still in the file.
findings_open_count() {
  local file
  file="$(findings_path "$1")"
  [[ -f "$file" ]] || {
    printf '0\n'
    return 0
  }
  grep -c '^- \[ \] ' "$file" || true
}
